enum user_input_name{ACCEL, BRAKE, LEFT_STEER, RIGHT_STEER, STEER_MODE, NUM_DUMMY};
enum torcs_output_name{CC_TRIGGER, LKAS_TRIGGER, SPEED, STEER_VALUE, RPM, YAW_RATE, DISTANCE, PASSED_TIME, TARGET_SPEED, ACCEL_VALUE, TARGET_RPM, IS_RUNNING, WHEEL_SPEED, TARGET_WHEEL_SPEED};
